In [33]:
import numpy as np

In [34]:
adj = [[0,1,1,0,0],
       [1,0,1,0,1],
       [1,1,0,1,0],
       [0,0,1,0,1],
       [0,1,0,1,0]]
adj = np.array(adj)

The graph looks like this:
```
   1
  / \
 2---3
 |   |
 5---4
```

In [48]:
v1 = [1,1,0,0,0]  # contiguous
v2 = [1,1,0,0,1]  # not contiguous
v3 = [1,0,1,0,1]  # contiguous

Basic linear algebra operations
https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

In [69]:
# dot product or inner product
np.dot(v1,v2)

2

In [70]:
# outer product
np.outer(v1,v2)

array([[1, 1, 0, 0, 1],
       [1, 1, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [59]:
# matrix multiplication
np.matmul(adj, adj)

array([[2, 1, 1, 1, 1],
       [1, 3, 1, 2, 0],
       [1, 1, 3, 0, 2],
       [1, 2, 0, 2, 0],
       [1, 0, 2, 0, 2]])

In [63]:
# matrix multiplication with the @ sign
v1@adj

array([1, 1, 2, 0, 1])

In [61]:
# raising a square matrix to a certain power
np.linalg.matrix_power(adj,5)

array([[16, 22, 22, 14, 14],
       [22, 18, 34, 10, 26],
       [22, 34, 18, 26, 10],
       [14, 10, 26,  4, 20],
       [14, 26, 10, 20,  4]])

In [65]:
# element-wise addition
adj + adj

array([[0, 2, 2, 0, 0],
       [2, 0, 2, 0, 2],
       [2, 2, 0, 2, 0],
       [0, 0, 2, 0, 2],
       [0, 2, 0, 2, 0]])

In [71]:
# element-wise multiplication
np.outer(v1,v2) * adj

array([[0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# Experimentations